// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Country struct {
	ID              int64          `json:"id"`
	Name            string         `json:"name"`
	Capital         sql.NullString `json:"capital"`
	Region          sql.NullString `json:"region"`
	Population      int64          `json:"population"`
	CurrencyCode    sql.NullString `json:"currency_code"`
	ExchangeRate    sql.NullString `json:"exchange_rate"`
	EstimatedGdp    sql.NullString `json:"estimated_gdp"`
	FlagUrl         sql.NullString `json:"flag_url"`
	LastRefreshedAt sql.NullTime   `json:"last_refreshed_at"`
}
